# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
---
# Site Info
title:              "Rafal Makara - Blog"
description:        "Blog o wytwarzaniu oprogramowania z punktu widzenia zarówno programisty, jak i managera. Jeżeli jesteś zainteresowany tworzeniem oprogrmaowania z uwzględnieniem obydwu tych perspektyw to ten blog jest dla Ciebie."
author_name:        "Rafał Makara"
logo_url:           https://avatars0.githubusercontent.com/u/1880231?v=4
twitter_username:   rafalmakara
github_username:    rmakara

# Site Settings
url:                https://rmakara.github.io
baseurl:            /
permalink:          /:title # Post permalink
timezone:           Europe/Warsaw # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            false  # enables support for mathjax - set to 'false' to disable
repository:         rmakara/rmakara.github.io

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins_dir:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme  

remote_theme: heiswayi/the-plain

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
